#!/bin/sh

ZIP=02143

xmodmap "/home/andrew/.Xmodmap"
nm-applet &
parcellite &
xflux -z $ZIP
$HOME/bin/tmux-start.sh &
dropbox &
xscreensaver -no-splash &
transmission-gtk &

exec fluxbox
# or if you want to keep a log:
#exec fluxbox -log "/home/andrew/.fluxbox/log"
