#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias pac="yaourt --noconfirm -y"
alias pacu="pac -Syu"  
alias picocom="picocom -l"
alias pbinclip='xclip -o | pastebincl | grep URL | cut -c 6- | xclip'
alias sshb="ssh -fN"
alias urxvt_lock="urxvt -si -sw -sk"
alias gemi='gem install --no-rdoc'
alias dmesg_t='watch "dmesg | tail"'
alias b2d_go='sudo modprobe vboxnetadp && boot2docker up && $(boot2docker shellinit) && boot2docker ip'
alias mem_total="vmstat -s -S M | grep 'total memory' | cut -c -15 | sed 's/^ *//'"
alias mem_free="vmstat -s -S M | grep 'free memory' | cut -c -15 | sed 's/^ *//'"

export PATH="$HOME/bin:$PATH"  
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
